---
- hosts: webserver
  become: yes
  become_user: root
  tasks:

  - name: "Installing Apache-Webserver."
    yum: name=httpd state=present

  - name: "Installing PhP."
    yum: name=php state=present

  - name: "Copying Local Website."
    copy: src=/home/ubuntu/website/ dest=/var/www/html/

  - name: "Creating Php InfoPage."
    copy: content="<?php phpinfo(); ?>" dest=/var/www/html/info.php

  - name: "Restarting Web-server."
    service: name=httpd state=restarted enabled=yes
